name: build

on:
  push:
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "8.0.*" # The .NET SDK version to use

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Tools
        run: dotnet tool restore

      - name: Configure Husky
        run: dotnet husky install

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Tools
        run: dotnet tool restore

      - name: Configure Husky
        run: dotnet husky install
      - name: Run Format Task
        run: dotnet husky run --name format

  style:
    name: Style
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Tools
        run: dotnet tool restore

      - name: Configure Husky
        run: dotnet husky install
      - name: Run Style Task
        run: dotnet husky run --name style

  analyzers:
    name: Analyzers
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Tools
        run: dotnet tool restore

      - name: Configure Husky
        run: dotnet husky install
      - name: Run Analyzers Task
        run: dotnet husky run --name analyzers

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [format, style, analyzers, spelling]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
