name: build

on:
  push:
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "8.0.*" # The .NET SDK version to use

jobs:
  setup:
    name: Setup

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Tools
        run: dotnet tool restore

      - name: Configure Husky
        run: dotnet husky install

  format:
      name: Format
      needs: setup
      steps:
        - name: Run Format Task
          run: dotnet husky run --name format

  style:
    name: Style
    needs: setup
    steps:
      - name: Run Style Task
        run: dotnet husky run --name style

  analyzers:
    name: Analyzers
    needs: setup
    steps:
      - name: Run Analyzers Task
        run: dotnet husky run --name analyzers

  spelling:
    name: Spelling
    needs: setup
    steps:
      - name: Run Spelling Task
        run: dotnet husky run --name spelling

  build:
    name: build-${{matrix.os}}
    needs: [format, style, analyzers, spelling]

    steps:
      - name: Install Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
